#
# CREATION KIT PLATFORM EXTENDED SETTINGS
#
# NOTICE: Experimental options may speed up things. They might do nothing. They might crash the editor.
#

[CreationKit]
bUIHotkeys=true							# [Experimental] Allow rebinding certain window hotkeys. See [Hotkeys] section.
bBSPointerHandleExtremly=false			# [Experimental] Increase the maximum number of refs to 8.388.608. This option reduces the allowed number of internal duplicates of one ref to 255, for synchronization between threads. Use it at your own risk.
bVersionControlMergeWorkaround=false	# [Experimental] Workaround for version control not allowing merges with more than 2 masters present. Do NOT use this for anything else.
bRefLinkGeometryHangWorkaround=false	# [Experimental] Workaround for bookshelves or 'Select Enable State Parent' causing the CK to hang. Ref link lines will no longer be visible.
bEnableStateParentWorkaround=false		# [Experimental] Workaround for 'Select Enable State Parent' selecting objects outside of the current cell or worldspace.
bIgnoreGroundHeightTest=false			# [Experimental] Removes the error message when during navmesh generation in a Worldspace with 'No Landscape' flag. Do NOT use this for anything else.

bGenerateCrashdumps=true				# Generate a dump in the game folder when the CK crashes.
bUnicode=false							# Translates UTF8 to ANSI when opening the plugin and back when saving.
bRenderWindowVSync=true					# Enabling vertical synchronization.
bDisableAssertions=false              	# Remove assertion message popups (not recommended).
bSkipTopicInfoValidation=true			# Speed up initial plugin load by skipping topic info validation, it doesn't matter if forms validation is disabled (recommended - fix crashes).
bAllowSaveESM=true						# Allow saving master files directly & setting them as the active file in the Data File dialog. This will destroy version control information.
bAllowMasterESP=true					# Allow ESP files to act as master files while saving.
bUIClassicTheme=false					# Enable classic theme. Incompatible with bUIDarkTheme and may cause graphical problems.
bUIDarkTheme=true						# Enable dark theme. Requires a Windows theme with styling (Aero) to be enabled and may cause graphical problems.
uUIDarkThemeId=1						# Theme version, 0 - lighter, 1 - darker, 2 - night blue, 3 - custom.
bLipDebugOutput=false					# Enable verbose logging output when generating LIP files (In version 1.6.1130 and later, does not work).
bOwnArchiveLoader=true					# Loading mod archives.
bNavMeshPseudoDelete=false				# Remove a triangle from a navmesh without deleting it.
bWarningCreateTexture2D=false			# Make CK react to poor texture loading.

# Options that are linked to the version of the editor, read the description

bSupportFormat171=true					# Includes support new format for editors older than 1.6.1130. Attention, the plugins will be saved in a new format. There is support for compact form indexes.
bOverlapsGenerateONAM=true				# (Only version 1.6.1130 or newer) Replaces the generating ONAM algorithm when saving to the master file, increasing the number of valid forms from 65.536 to 4.294.967.296. If you received a crash during saving .esm, it makes sense to enable the option.

# Set charset for font ListView, ListBox, TreeView controls (worked only bUIDarkTheme > 0)
# ANSI_CHARSET				0
# DEFAULT_CHARSET			1
# SYMBOL_CHARSET			2
# SHIFTJIS_CHARSET			128
# HANGUL_CHARSET			129
# GB2312_CHARSET			134
# CHINESEBIG5_CHARSET		136
# OEM_CHARSET				255
# JOHAB_CHARSET				130
# HEBREW_CHARSET			177
# ARABIC_CHARSET			178
# GREEK_CHARSET				161
# TURKISH_CHARSET			162
# VIETNAMESE_CHARSET		163
# THAI_CHARSET				222
# EASTEUROPE_CHARSET		238
# RUSSIAN_CHARSET			204
# MAC_CHARSET				77
# BALTIC_CHARSET			186
nCharset=1

[Crashes]
bGenerateFullDump=false					# Generates a full dump with more information, including personal information. Use it yourself to find the cause of the crash. Tool WinDbg x64 from Windows SDK.

[Graphics]
fMipLODBias=-1.3						# Force set mipmap level bias value (value must be [-5.0 : 5.0] where there is less than 0.0, the further away the 0 mipmap is).
uMaxAnisotropy=16						# Distortion visible in the texels of a three-dimensional object whose surface is oriented at an angle relative to the screen plane is called anisotropy (value must be [0 : 16]).
fTAAJitter=0.125						# Fake frame offset, creating effect of frame movement, using bilinear texture (value must be [0.0 : 0.5]).
fStepInRender=30.0						# Number of units when moving in the rendering window as in Starfield (value must be [15.0 : 100.0]).

[FaceGen]
bAutoCompressionDDS=true				# Texture compression during generation
bDisableAutoFaceGen=true				# Prevent facegen data from being created on plugin save
bDisableExportDDS=false					# Prevent tint export as DDS
bDisableExportTGA=true					# Prevent tint export as TGA
bDisableExportNIF=false					# Prevent facegen geometry export
uTintMaskResolution=1024				# Sets NxN resolution when exporting textures

[Log]
bShowWindow=true						# Initial log window show or hide.
nX=64									# Initial log window X coordinate.
nY=64									# Initial log window Y coordinate.
nWidth=1024								# Initial log window width. Set to 0 to hide the log.
nHeight=480								# Initial log window height. Set to 0 to hide the log.
nFontSize=10							# Size in points.
uFontWeight=400							# Light (300), Regular (400), Medium (500), Bold (700).
sFont='Consolas'						# Any installed system font.
sOutputFile='ckpe.log'					# Print log output to a file (i.e. 'log.txt'). May cause UI lag on slow hard drives. To disable, set the value to 'none'.

#
# Bind custom keys for the Render Window & Navmesh Edit Window. bUIHotkeys must be enabled under [CreationKit].
#
# Allowed keys: A-Z, a-z, 0-9, ESC, DEL, TAB, and most symbols. Allowed modifiers: CTRL, SHIFT, and ALT. Spaces and quotes will be ignored.
#
[Hotkeys]
HKFunc_AddPolygon='A'                                        # Add a polygon
HKFunc_AlignToPosition='CTRL+SHIFT+A'                        # Align to position
HKFunc_AlignToRotation='CTRL+A'                              # Align to rotation
HKFunc_AnchorCamera='SHIFT+F'                                # Anchor the camera
HKFunc_ChangeDrawMode='W'                                    # Change draw mode
HKFunc_ClearSelection='D'                                    # Clear selection
HKFunc_ClearSnapReference='ALT+Q'                            # Clear the snap reference
HKFunc_Copy='CTRL+C'                                         # Copy selection
HKFunc_CreateMultiboundReference='CTRL+B'                    # Create a multibound reference
HKFunc_CutSelection='CTRL+X'                                 # Cut selection
HKFunc_CycleSelectedVisibility='1'                           # Cycle the visibility of selected objects
HKFunc_CycleThroughCameraViews='Y'                           # Cycle camera view
HKFunc_DeleteNavMeshSelection='R'                            # Delete selection
HKFunc_DeleteSelection='DEL'                                 # Delete selection
HKFunc_DropCamera='ALT+Z'                                    # Drop camera
HKFunc_DropSelectionToGround='F'                             # Drop selection to ground
HKFunc_DropVerticesOrFloodFill='F'                           # Drop vertices/Flood Fill
HKFunc_Duplicate='CTRL+D'                                    # Duplicate selection
HKFunc_EditLandscape='H'                                     # Edit landscape
HKFunc_EditNavmesh='CTRL+E'                                  # Edit navmesh
HKFunc_FinalizeCell='CTRL+1'                                 # Finalize cell
HKFunc_FindCover='CTRL+2'                                    # Find cover
HKFunc_FlagWaterTris='CTRL+ALT+W'                            # Flag Water Triangles
HKFunc_FreezeCamera='3'                                      # Freeze the camera
HKFunc_HideSelectedNavMeshes='H'                             # Hide selected navmeshes
HKFunc_ImportObjectNavmeshes='CTRL+ALT+I'                    # Import Object Navmeshes
HKFunc_InverseFloodFill='I'                                  # Inverse flood fill
HKFunc_LinkOrBreakPlanesOrRooms='ALT+L'                      # Link/break planes/rooms
HKFunc_LoadCellForSelectedObject='CTRL+L'                    # Load selected object's parent cell
HKFunc_MergeSelectedVertices='Q'                             # Merge selected vertices
HKFunc_MoveClipboardReferences='CTRL+M'                      # Move clipboard references
HKFunc_MoveClipboardReferencesInPlace='CTRL+SHIFT+M'         # Move clipboard references in place
HKFunc_ObjectPalette='SHIFT+O'                               # Object palette
HKFunc_OpenAdvancedGenerationDialog='4'                      # Open advanced generation dialog
HKFunc_OpenEdgePropertiesDialog='E'                          # Open edge properties dialog
HKFunc_OpenStandardGenerationDialog='3'                      # Open standard generation dialog
HKFunc_Paste='CTRL+V'                                        # Paste clipboard contents
HKFunc_PasteInPlace='CTRL+SHIFT+V'                           # Paste clipboard contents in place
HKFunc_PickingPreferences='/'                                # Picking preferences
HKFunc_PlaceCameraAboveSelection='T'                         # Place camera above selection
HKFunc_RaiseSelection='ALT+G'                                # Raise selection
HKFunc_Redo='CTRL+Y'                                         # Redo
HKFunc_Refresh='F5'                                          # Refresh
HKFunc_ResetReferenceRotation='CTRL+K'                       # Reset rotation
HKFunc_RotateDoubleVertexSelection='TAB'                     # Rotate double vertex selection
HKFunc_RotateDoubleVertexSelectionWithControlKey='CTRL+TAB'  # Rotate double vertex selection
HKFunc_Save='CTRL+S'                                         # Save
HKFunc_SaveAndPushPluginPC='CTRL+SHIFT+S'                    # Save and push plugin to PC
HKFunc_SearchAndReplace='CTRL+F'                             # Search and replace
HKFunc_SelectTriangleByIndex='CTRL+F'                        # Select triangle by index
HKFunc_SetLightFadeScalingKeyDown='CTRL+ALT+S'               # Scale a light's fade distance
HKFunc_SetLightFOVScalingKeyDown='ALT+S'                     # Scale a light's FOV
HKFunc_SetLightSDBScalingKeyDown='ALT+B'                     # Scale a light's FOV
HKFunc_SetManipulationModeRotate='W'                         # Enter rotation manipulation mode
HKFunc_SetManipulationModeScale='2'                          # Enter scale manipulation mode
HKFunc_SetManipulationModeSelect='R'                         # Enter selection manipulation mode
HKFunc_SetManipulationModeTranslate='E'                      # Enter translation manipulation mode
HKFunc_SetScalingKeyDown='S'                                 # Scale a reference
HKFunc_ShowLandBorders='B'                                   # Show land borders
HKFunc_ShowNavCutters='CTRL+SHIFT+N'                         # Toggle Negative Navmesh Display
HKFunc_ShowSceneGraph='F10'                                  # Show scene graph
HKFunc_SnapDecrement='['                                     # Decrement snap units
HKFunc_SnapIncrement=']'                                     # Increment snap units
HKFunc_SnapReferences='SHIFT+K'                              # Resnap References
HKFunc_SwapEdge='S'                                          # Swap edge
HKFunc_SwapEditorWater='CTRL+W'                              # Swap editor water
HKFunc_ToggleBatchDialog='-'                                 # Toggle batch dialog
HKFunc_ToggleBrightLights='A'                                # Toggle bright lights
HKFunc_ToggleCellWindowLoads='ALT+A'                         # Toggle cell window loads
HKFunc_ToggleCollisionGeometry='F4'                          # Toggle collision geometry
HKFunc_ToggleDebugGeometry='4'                               # Toggle debug geometry
HKFunc_ToggleEdgeSelectMode='G'                              # Toggle edge select mode
HKFunc_ToggleEnableStateChildrenVisibility='CTRL+1'          # Toggle visibility of enable state children
HKFunc_ToggleEnableStateOppositeChildrenVisibility='SHIFT+1' # Toggle visibility of enable state opposite children
HKFunc_ToggleFlycam='`'                                      # Toggle flycam
HKFunc_ToggleFog='CTRL+5'                                    # Toggle fog
HKFunc_ToggleGizmoOrientation='G'                            # Toggle gizmo orientation
HKFunc_ToggleGrass='8'                                       # Toggle grass
HKFunc_ToggleGrid='='                                        # Toggle grid
HKFunc_ToggleHavok='ALT+H'                                   # Toggle havok
HKFunc_ToggleLandCulling='SHIFT+L'                           # Toggle land culling
HKFunc_ToggleLightMarkers='CTRL+I'                           # Toggle light markers
HKFunc_ToggleLightRadius='L'                                 # Toggle light radius
HKFunc_ToggleLocationSnap='Q'                                # Toggle location snap
HKFunc_ToggleMarkers='M'                                     # Toggle markers
HKFunc_ToggleNoLargeCreature='CTRL+L'                        # Toggle no large creature
HKFunc_ToggleNonlandCulling='SHIFT+C'                        # Toggle non-land culling
HKFunc_ToggleOcclusionPlanes='U'                             # Toggle occlusion planes
HKFunc_ToggleOrthographicPerspective='0'                     # Toggle orthographic perspective
HKFunc_TogglePickingAgainstTrees='CTRL+T'                    # Toggle picking against trees
HKFunc_TogglePortalMode='CTRL+P'                             # Toggle portal mode
HKFunc_TogglePreferredOrCreateLedgePortal='P'                # Toggle preferred or create ledge portal
HKFunc_ToggleReferenceSnap='SHIFT+Q'                         # Toggle reference snap
HKFunc_ToggleRotationSnap='CTRL+Q'                           # Toggle rotation snap
HKFunc_ToggleSelectionCulling='CTRL+SHIFT+C'                 # Toggle selection culling
HKFunc_ToggleShadows='5'                                     # Toggle shadows
HKFunc_ToggleSingleCellViewMode='N'                          # Toggle single cell view mode
HKFunc_ToggleSky='6'                                         # Toggle sky
HKFunc_ToggleSoundMarkers='CTRL+N'                           # Toggle sound markers
HKFunc_ToggleTrees='ALT+T'                                   # Toggle trees
HKFunc_ToggleTrianglesSelectable='T'                         # Toggle triangles selectable
HKFunc_ToggleVerticesSelectable='V'                          # Toggle vertices selectable
HKFunc_ToggleWater='O'                                       # Toggle water
HKFunc_ToggleWaterCulling='SHIFT+2'                          # Toggle water culling
HKFunc_ToggleWireframe='7'                                   # Toggle wireframe
HKFunc_Undo='CTRL+Z'                                         # Undo
HKFunc_UnhideAllNavMeshes='CTRL+H'                           # Unhide all navmeshes
HKFunc_UnhideAllObjects='ALT+1'                              # Unhide all hidden objects