#
# CREATION KIT PLATFORM EXTENDED SETTINGS
#
# NOTICE: Experimental options may speed up things. They might do nothing. They might crash the editor.
#
[CreationKit]
bVersionControlMergeWorkaround=false	# [Experimental] Workaround for version control not allowing merges with more than 2 masters present. Do NOT use this for anything else.

bDisableAssertions=false				# Remove assertion message popups (not recommended).
bGenerateCrashdumps=true				# Generate a dump in the game folder when the CK crashes.
bUnicode=false							# Translates UTF8 to ANSI when opening the plugin and back when saving.
bSkipTopicInfoValidation=true			# Speed up initial plugin load by skipping topic info validation, it doesn't matter if forms validation is disabled (recommended - fix crashes).
bAllowSaveESM=true						# Allow saving master files directly & setting them as the active file in the Data File dialog. This will destroy version control information.
bAllowMasterESP=true					# Allow ESP files to act as master files while saving.
bUIClassicTheme=false					# Enable classic theme. Incompatible with bUIDarkTheme and may cause graphical problems.
bUIDarkTheme=false						# Enable dark theme. Requires a Windows theme with styling (Aero) to be enabled and may cause graphical problems.

# Set charset for font ListView, ListBox, TreeView controls (worked only bUIDarkTheme > 0)
# ANSI_CHARSET				0
# DEFAULT_CHARSET			1
# SYMBOL_CHARSET			2
# SHIFTJIS_CHARSET			128
# HANGUL_CHARSET			129
# GB2312_CHARSET			134
# CHINESEBIG5_CHARSET		136
# OEM_CHARSET				255
# JOHAB_CHARSET				130
# HEBREW_CHARSET			177
# ARABIC_CHARSET			178
# GREEK_CHARSET				161
# TURKISH_CHARSET			162
# VIETNAMESE_CHARSET		163
# THAI_CHARSET				222
# EASTEUROPE_CHARSET		238
# RUSSIAN_CHARSET			204
# MAC_CHARSET				77
# BALTIC_CHARSET			186
nCharset=1

[Crashes]
bGenerateFullDump=false					# Generates a full dump with more information, including personal information. Use it yourself to find the cause of the crash. Tool WinDbg x64 from Windows SDK.

[Log]
bShowWindow=true						# Initial log window show or hide.
bAllowOutputNetworkActivity=false		# Display information about sending network packets to Bethesda servers.
nX=64									# Initial log window X coordinate.
nY=64									# Initial log window Y coordinate.
nWidth=1024								# Initial log window width. Set to 0 to hide the log.
nHeight=480								# Initial log window height. Set to 0 to hide the log.
nFontSize=10							# Size in points.
uFontWeight=400							# Light (300), Regular (400), Medium (500), Bold (700).
sFont='Consolas'						# Any installed system font.
sOutputFile='ckpe.log'					# Print log output to a file (i.e. "log.txt"). May cause UI lag on slow hard drives. To disable, set the value to "none".