#
# CREATION KIT PLATFORM EXTENDED SETTINGS
#
# NOTICE: Experimental options may speed up things. They might do nothing. They might crash the editor.
#

[CreationKit]

# [Experimental] Allow rebinding certain window hotkeys. See [Hotkeys] section.
bUIHotkeys = true

# [Experimental] Workaround for version control not allowing merges with more than 2 masters present. Do NOT use this for anything else.
bVersionControlMergeWorkaround = false

# [Experimental] Increase the maximum number of refs to 67.108.864 (for NG2 8.388.608). Use it at your own risk.
bBSPointerHandleExtremly = false

# Abandoning outdated "profile" functions, using the cache, for fast reading and saving options.
bINICache = true

# Generate a dump in the game folder when the CK crashes.
bGenerateCrashdumps = true

# Translates UTF8 to ANSI when opening the plugin and back when saving.
bUnicode = false

# Enabling vertical synchronization.
bRenderWindowVSync = true

# Remove assertion message popups (not recommended).
bDisableAssertions = false

# Speed up initial plugin load by skipping topic info validation, it doesn't matter if forms validation is disabled (recommended - fix crashes).
bSkipTopicInfoValidation = true

# Allow saving master files directly & setting them as the active file in the Data File dialog. This will destroy version control information.
bAllowSaveESM = true

# Allow ESP files to act as master files while saving.
bAllowMasterESP = true

# Enable classic theme. Incompatible with bUIDarkTheme and may cause graphical problems.
bUIClassicTheme = false

# Enable dark theme. Requires a Windows theme with styling (Aero) to be enabled and may cause graphical problems.
bUIDarkTheme = true

# Theme version, 0 - lighter, 1 - darker, 2 - night blue, 3 - custom.
uUIDarkThemeId = 1

# Make CK react to poor texture loading.
bWarningCreateTexture2D = false

# Set charset for font ListView, ListBox, TreeView controls (worked only bUIDarkTheme > 0)
# ANSI_CHARSET				0
# DEFAULT_CHARSET			1
# SYMBOL_CHARSET			2
# SHIFTJIS_CHARSET			128
# HANGUL_CHARSET			129
# GB2312_CHARSET			134
# CHINESEBIG5_CHARSET		136
# OEM_CHARSET				255
# JOHAB_CHARSET				130
# HEBREW_CHARSET			177
# ARABIC_CHARSET			178
# GREEK_CHARSET				161
# TURKISH_CHARSET			162
# VIETNAMESE_CHARSET		163
# THAI_CHARSET				222
# EASTEUROPE_CHARSET		238
# RUSSIAN_CHARSET			204
# MAC_CHARSET				77
# BALTIC_CHARSET			186
nCharset = 1


# This patch is harmful to PreVis. 
# Therefore, these parameters are set only when the command "-GeneratePreCombined" is called from the console. 
[PreCombined]

# This of option control the output of the havok collision information generated during the precombine process, which is stuck at mode 1 unpatched.
# This will not magically make your plugin the same format. - BenRierimanu
# 0 - 64bit havok little endian [PC or XB1, default setting with CKPE and recommended for PRP and related patches]
# 1 - 64bit havok big endian [PS4, default setting unpatched. Untested and not recommended unless you can somehow get the files on that platform]
# 2 - 32bit havok little endian [PC or XB1, default setting when using the user interface generation commands as the XB1 was originally a 32bit platform at one point, will still work, but obsolete]
nGenerationVersion = 0


[Animation]

# Skips animation data generation, significantly speeds up loading, however, if you are working with animation, it should be disabled.
bSkipAnimationBuildData = false


[Crashes]

# Generates a full dump with more information, including personal information. Use it yourself to find the cause of the crash. Tool WinDbg x64 from Windows SDK.
bGenerateFullDump = false


[Graphics]

# Force set mipmap level bias value (value must be [-3.0 : 3.0] where there is less than 0.0, the further away the 0 mipmap is).
fMipLODBias = -1.3

# Distortion visible in the texels of a three-dimensional object whose surface is oriented at an angle relative to the screen plane is called anisotropy (value must be [0 : 16]).
uMaxAnisotropy = 16

# Fake frame offset, creating effect of frame movement, using bilinear texture (value must be [0.0 : 0.5]).
fTAAJitter = 0.125

# Number of units when moving in the rendering window as in Starfield (value must be [15.0 : 100.0]).
fStepInRender = 30.0


[FaceGen]

# Texture compression during generation.
bAutoCompressionDDS = true

# Prevent tint export as DDS.
bDisableExportDDS = false

# Prevent tint export as TGA.
bDisableExportTGA = true

# Prevent facegen geometry export.
bDisableExportNIF = false

# Sets NxN resolution when exporting textures.
uTintMaskResolution = 2048


[LipGen]

# Supported languages:
# USEnglish
# French
# German
# Spanish
# Italian
# Korean
# Japanese
# Specifies the language.
sLanguage = 'USEnglish'

# Specifies the gesture exaggeration.
fGestureExaggeration = 1.0


[Log]

# Initial log window show or hide.
bShowWindow = true

# Initial log window X coordinate.
nX = 64

# Initial log window Y coordinate.
nY = 64

# Initial log window width. Set to 0 to hide the log.
nWidth = 1024

# Initial log window height. Set to 0 to hide the log.
nHeight = 480

# Size in points.
nFontSize = 10

# Light (300), Regular (400), Medium (500), Bold (700).
uFontWeight = 400

# Any installed system font.
sFont = 'Consolas'

# Print log output to a file (i.e. "log.txt"). May cause UI lag on slow hard drives. To disable, set the value to "none".
sOutputFile = 'ckpe.log'


#
# Bind custom keys for the Render Window & Navmesh Edit Window. bUIHotkeys must be enabled under [CreationKit].
#
# Allowed keys: A-Z, a-z, 0-9, ESC, DEL, TAB, and most symbols. Allowed modifiers: CTRL, SHIFT, and ALT. Spaces and quotes will be ignored.
#
[Hotkeys]

# Anchor the camera
HKFunc_AnchorCamera = 'SHIFT+F'

# Cycle camera view
HKFunc_CycleThroughCameraViews = 'Y'

# Toggle non-land culling
HKFunc_ToggleNonlandCulling = 'SHIFT+C'

# Clear selection
HKFunc_ClearSelection = 'D'

# Copy selection
HKFunc_Copy = 'CTRL+C'

# Cut selection
HKFunc_CutSelection = 'CTRL+X'

# Delete selection
HKFunc_DeleteSelection = 'DEL'

# Drop camera
HKFunc_DropCamera = 'CTRL+ALT+Z'

# Duplicate selection
HKFunc_Duplicate = 'CTRL+D'

# Edit landscape
HKFunc_EditLandscape = 'H'

# Edit navmesh
HKFunc_EditNavmesh = 'CTRL+E'

# Go to selection in game
HKFunc_GoToSelectionInGame = 'SHIFT+G'

# Object palette
HKFunc_ObjectPalette = 'SHIFT+O'

# Paste clipboard contents
HKFunc_Paste = 'CTRL+V'

# Paste clipboard contents in place
HKFunc_PasteInPlace = 'SHIFT+CTRL+V'

# Picking preferences
HKFunc_PickingPreferences = '/'

# Redo
HKFunc_Redo = 'CTRL+Y'

# Refresh
HKFunc_Refresh = 'F5'

# Refresh and clear undo list
HKFunc_RefreshAndClearUndoList = 'CTRL+ALT+F5'

# Refresh selected
HKFunc_RefreshSelected = 'ALT+F5'

# Save
HKFunc_Save = 'CTRL+S'

# Scale a light's fade distance
HKFunc_SetLightFadeScalingKeyDown = 'CTRL+ALT+S'

# Scale a light's FOV
HKFunc_SetLightFOVScalingKeyDown = 'ALT+S'

# Scale a light's FOV
HKFunc_SetLightSDBScalingKeyDown = 'ALT+B'

# Set local rotation
HKFunc_SetLocalRotation = 'ALT+G'

# Scale a reference
HKFunc_SetScalingKeyDown = 'S'

# Toggle gizmo orientation
HKFunc_ToggleGizmoOrientation = 'G'

# Toggle havok
HKFunc_ToggleHavok = 'ALT+H'

# Enter selection manipulation mode
HKFunc_SetManipulationModeSelect = 'R'

# Enter rotation manipulation mode
HKFunc_SetManipulationModeRotate = 'W'

# Enter translation manipulation mode
HKFunc_SetManipulationModeTranslate = 'E'

# Enter scale manipulation mode
HKFunc_SetManipulationModeScale = '2'

# Show land borders
HKFunc_ShowLandBorders = 'B'

# Show scene graph
HKFunc_ShowSceneGraph = 'F10'

# Export selected scene to FBX file
HKFunc_ToFBX = 'F2'

# Decrement snap units
HKFunc_SnapDecrement = '['

# Increment snap units
HKFunc_SnapIncrement = ']'

# Toggle bright lights
HKFunc_ToggleBrightLights = 'A'

# Toggle cell window loads
HKFunc_ToggleCellWindowLoads = 'ALT+A'

# Toggle collision geometry
HKFunc_ToggleCollisionGeometry = 'F4'

# Toggle fog
HKFunc_ToggleFog = 'CTRL+5'

# Toggle game FOV camera
HKFunc_ToggleGameFOV = 'ALT+F'

# Toggle grass
HKFunc_ToggleGrass = '8'

# Toggle grid
HKFunc_ToggleGrid = '='

# Toggle land culling
HKFunc_ToggleLandCulling = 'SHIFT+L'

# Toggle light markers
HKFunc_ToggleLightMarkers = 'CTRL+I'

# Toggle light radius
HKFunc_ToggleLightRadius = 'L'

# Toggle lighting-only mode
HKFunc_ToggleLightingOnlyMode = 'CTRL+ALT+L'

# Toggle markers
HKFunc_ToggleMarkers = 'M'

# Toggle occlusion planes
HKFunc_ToggleOcclusionPlanes = 'U'

# Toggle orthographic perspective
HKFunc_ToggleOrthographicPerspective = '0'

# Toggle picking against trees
HKFunc_TogglePickingAgainstTrees = 'CTRL+T'

# Toggle the reference properties window
HKFunc_TogglePropertiesWindow = 'ENTER'

# Toggle rooms and portals
HKFunc_ToggleRoomsAndPortals = 'SHIFT+R'

# Toggle shadows
HKFunc_ToggleShadows = '5'

# Toggle sky
HKFunc_ToggleSky = '6'

# Toggle sound markers
HKFunc_ToggleSoundMarkers = 'CTRL+N'

# Toggle trees
HKFunc_ToggleTrees = 'ALT+T'

# Toggle wireframe
HKFunc_ToggleWireframe = '7'

# Toggle water culling
HKFunc_ToggleWaterCulling = 'SHIFT+2'

# Undo
HKFunc_Undo = 'CTRL+Z'

# Save and push plugin to PC
HKFunc_SaveAndPushPluginPC = 'SHIFT+CTRL+S'

# Run Object Combination
HKFunc_RunObjectCombination = 'SHIFT+CTRL+ALT+O'

# Preview Object Combination
HKFunc_ToggleObjectCombinationPreview = 'SHIFT+CTRL+O'

# Preview Object Combination Groups
HKFunc_ToggleObjectCombinationGroupPreview = 'CTRL+O'

# Align to rotation
HKFunc_AlignToRotation = 'CTRL+A'

# Align to position
HKFunc_AlignToPosition = 'SHIFT+CTRL+A'

# Load Last Cell
HKFunc_LoadLastCell = 'CTRL+TAB'

# Clear the snap reference
HKFunc_ClearSnapReference = 'ALT+Q'

# Create a bendable spline
HKFunc_CreateBendableSpline = 'P'

# Create a linked ref chain
HKFunc_CreateLinkedRefChain = 'SHIFT+CTRL+SPACE'

# Create a multibound reference
HKFunc_CreateMultiboundReference = 'CTRL+B'

# Cycle the visibility of selected objects
HKFunc_CycleSelectedVisibility = '1'

# Cycle the visibility of unselected objects
HKFunc_CycleUnselectedVisibility = 'SHIFT+ALT+1'

# Drop selection to ground
HKFunc_DropSelectionToGround = 'F'

# Duplicate and link reference
HKFunc_DuplicateAndLink = 'CTRL+ALT+D'

# Fill the material palette from current selection
HKFunc_FillMaterialPalette = 'ALT+M'

# Fragment static collection
HKFunc_FragmentStaticCollection = 'ALT+U'

# Freeze the camera
HKFunc_FreezeCamera = '3'

# Group references
HKFunc_GroupReferences = 'CTRL+G'

# Link/break planes/rooms
HKFunc_LinkOrBreakPlanesOrRooms = 'ALT+L'

# Load selected object's parent cell
HKFunc_LoadCellForSelectedObject = 'CTRL+L'

# Make static collection
HKFunc_MakeStaticCollection = 'ALT+O'

# Match slope while dragging
HKFunc_MatchSlopeWhileDragging = 'ALT+'

# Move clipboard references
HKFunc_MoveClipboardReferences = 'CTRL+M'

# Move clipboard references in place
HKFunc_MoveClipboardReferencesInPlace = 'SHIFT+CTRL+M'

# Move selection to cursor
HKFunc_MoveSelectionToCursor = 'ALT+N'

# Enter paint selection mode
HKFunc_PaintSelection = 'SHIFT+CTRL+'

# Place camera above selection
HKFunc_PlaceCameraAboveSelection = 'T'

# Quick link
HKFunc_QuickLink = 'CTRL+SPACE'

# Raise selection
HKFunc_RaiseSelection = 'CTRL+ALT+G'

# Reset rotation
HKFunc_ResetReferenceRotation = 'CTRL+K'

# Reset scale
HKFunc_ResetReferenceScale = 'SHIFT+CTRL+K'

# Resnap References
HKFunc_SnapReferences = 'SHIFT+K'

# Search and replace
HKFunc_SearchAndReplace = 'CTRL+F'

# Select adjoining references
HKFunc_SelectAdjoiningReferences = 'CTRL+ENTER'

# Select all adjoining references
HKFunc_SelectAllAdjoiningReferences = 'SHIFT+CTRL+ENTER'

# Toggle batch dialog
HKFunc_ToggleBatchDialog = '-'

# Toggle debug geometry
HKFunc_ToggleDebugGeometry = '4'

# Toggle visibility of enable state opposite children
HKFunc_ToggleEnableStateOppositeChildrenVisibility = 'SHIFT+1'

# Toggle visibility of enable state children
HKFunc_ToggleEnableStateChildrenVisibility = 'CTRL+1'

# Toggle flycam
HKFunc_ToggleFlycam = '`'

# Toggle location snap
HKFunc_ToggleLocationSnap = 'Q'

# Toggle portal mode
HKFunc_TogglePortalMode = 'CTRL+P'

# Toggle reference snap
HKFunc_ToggleReferenceSnap = 'SHIFT+Q'

# Toggle rotation snap
HKFunc_ToggleRotationSnap = 'CTRL+Q'

# Toggle selection culling
HKFunc_ToggleSelectionCulling = 'SHIFT+CTRL+C'

# Toggle selection mask
HKFunc_ToggleSelectionMask = 'ALT+V'

# Ungroup references
HKFunc_UngroupReferences = 'CTRL+U'

# Unhide all hidden objects
HKFunc_UnhideAllObjects = 'ALT+1'

# Add a polygon
HKFunc_AddPolygon = 'A'

# Change draw mode
HKFunc_ChangeDrawMode = 'W'

# Delete selection
HKFunc_DeleteNavMeshSelection = 'R'

# Drop vertices/Flood Fill
HKFunc_DropVerticesOrFloodFill = 'F'

# Finalize cell
HKFunc_FinalizeCell = 'CTRL+1'

# Find cover
HKFunc_FindCover = 'CTRL+2'

# Hide selected triangles
HKFunc_ToggleHiddenForSelectedTris = '1'

# Unhide all hidden triangles
HKFunc_UnhideAllTris = 'ALT+1'

# Inverse flood fill
HKFunc_InverseFloodFill = 'I'

# Merge selected vertices
HKFunc_MergeSelectedVertices = 'Q'

# Open advanced generation dialog
HKFunc_OpenAdvancedGenerationDialog = '4'

# Open edge properties dialog
HKFunc_OpenEdgePropertiesDialog = 'E'

# Open standard generation dialog
HKFunc_OpenStandardGenerationDialog = '3'

# Rotate double vertex selection
HKFunc_RotateDoubleVertexSelection = 'TAB'

# Rotate double vertex selection
HKFunc_RotateDoubleVertexSelectionWithControlKey = 'CTRL+TAB'

# Select triangle by index
HKFunc_SelectTriangleByIndex = 'CTRL+F'

# Swap edge
HKFunc_SwapEdge = 'S'

# Shrink triangle selection
HKFunc_ShrinkTriangleSelection = 'SHIFT+S'

# Toggle edge select mode
HKFunc_ToggleEdgeSelectMode = 'G'

# Grow triangle selection
HKFunc_GrowTriangleSelection = 'SHIFT+A'

# Toggle no large creature
HKFunc_ToggleNoLargeCreature = 'CTRL+L'

# Toggle Floating creature flag
HKFunc_ToggleFloat = 'CTRL+ALT+F'

# Toggle preferred or create ledge portal
HKFunc_TogglePreferredOrCreateLedgePortal = 'P'

# Toggle single cell view mode
HKFunc_ToggleSingleCellViewMode = 'N'

# Sets current cell as active cell
HKFunc_SetCurrentCell = 'CTRL+N'

# Toggle triangles selectable
HKFunc_ToggleTrianglesSelectable = 'T'

# Toggle vertices selectable
HKFunc_ToggleVerticesSelectable = 'V'

# Toggle water
HKFunc_ToggleWater = 'O'

# Import Object Navmeshes
HKFunc_ImportObjectNavmeshes = 'CTRL+ALT+I'

# Toggle Negative Navmesh Display
HKFunc_ShowNavCutters = 'SHIFT+CTRL+N'

# Flag Water Triangles
HKFunc_FlagWaterTris = 'CTRL+ALT+W'

# Generate waypoints for selection
HKFunc_GenerateWaypointsForSelection = 'SHIFT+CTRL+G'

# Clear waypoints for selection
HKFunc_ClearWaypointsForSelection = 'SHIFT+CTRL+C'

# Create Precut for selection
HKFunc_CreatePrecutsForSelection = 'C'

# Link Precut for selection
HKFunc_LinkPrecutsForSelection = 'L'

# Clear Precut for selection
HKFunc_ClearPrecutsForSelection = 'ALT+L'
