#pragma once

#include <EditorAPI/B/BaseFormComponent.h>
#include <EditorAPI/B/BGSClasses.h>
#include <EditorAPI/B/BGSDestructibleObjectForm.h>
#include <EditorAPI/B/BGSEquipSlot.h>
#include <EditorAPI/B/BGSEquipType.h>
#include <EditorAPI/B/BGSFootstepSet.h>
#include <EditorAPI/B/BGSImpactData.h>
#include <EditorAPI/B/BGSImpactDataSet.h>
#include <EditorAPI/B/BGSKeyword.h>
#include <EditorAPI/B/BGSLocalizedString.h>
#include <EditorAPI/B/BGSLocationRefType.h>
#include <EditorAPI/B/BGSMaterialType.h>
#include <EditorAPI/B/BGSMessageIcon.h>
#include <EditorAPI/B/BGSPickHandler.h>
#include <EditorAPI/B/BGSPrimitive.h>
#include <EditorAPI/B/BGSRenderWindow.h>
#include <EditorAPI/B/BGSRenderWindowCamera.h>
#include <EditorAPI/B/BGSSounds.h>
#include <EditorAPI/B/BGSTextureSet.h>
#include <EditorAPI/B/BGSVoiceType.h>
#include <EditorAPI/B/BSDynamicTriShape.h>
#include <EditorAPI/B/BSEffectShaderMaterial.h>
#include <EditorAPI/B/BSEntryString.h>
#include <EditorAPI/B/BSExtraData.h>
#include <EditorAPI/B/BSFadeNode.h>
#include <EditorAPI/B/BSFile.h>
#include <EditorAPI/B/BSFixedString.h>
#include <EditorAPI/B/BSGeometry.h>
#include <EditorAPI/B/BSGraphicsRenderTargetManager.h>
#include <EditorAPI/B/BSGraphicsTypes.h>
#include <EditorAPI/B/BSHandleRefObject.h>
#include <EditorAPI/B/BSLines.h>
#include <EditorAPI/B/BSLock.h>
#include <EditorAPI/B/BSOcclusionPlane.h>
#include <EditorAPI/B/BSPointerHandleManager.h>
#include <EditorAPI/B/BSReadWriteLock.h>
#include <EditorAPI/B/BSResources.h>
#include <EditorAPI/B/BSShaderMaterial.h>
#include <EditorAPI/B/BSShaderProperty.h>
#include <EditorAPI/B/BSShaderResourceManager.h>
#include <EditorAPI/B/BSSpinLock.h>
#include <EditorAPI/B/BSString.h>
#include <EditorAPI/B/BSStringCache.h>
#include <EditorAPI/B/BSSystemFile.h>
#include <EditorAPI/B/BSTArray.h>
#include <EditorAPI/B/BSTextureSet.h>
#include <EditorAPI/B/BSTList.h>

#include <EditorAPI/D/DecalData.h>

#include <EditorAPI/N/NiAVObject.h>
#include <EditorAPI/N/NiCollisionObject.h>
#include <EditorAPI/N/NiCollisionUtils.h>
#include <EditorAPI/N/NiColor.h>
#include <EditorAPI/N/NiFlags.h>
#include <EditorAPI/N/NiMatrix.h>
#include <EditorAPI/N/NiMemoryManager.h>
#include <EditorAPI/N/NiNode.h>
#include <EditorAPI/N/NiObject.h>
#include <EditorAPI/N/NiObjectNET.h>
#include <EditorAPI/N/NiPick.h>
#include <EditorAPI/N/NiPoint.h>
#include <EditorAPI/N/NiPointer.h>
#include <EditorAPI/N/NiProperty.h>
#include <EditorAPI/N/NiRefObject.h>
#include <EditorAPI/N/NiRTTI.h>
#include <EditorAPI/N/NiSkinInstance.h>
#include <EditorAPI/N/NiSourceTexture.h>
#include <EditorAPI/N/NiTArray.h>
#include <EditorAPI/N/NiTexture.h>
#include <EditorAPI/N/NiTimeController.h>
#include <EditorAPI/N/NiTMap.h>
#include <EditorAPI/N/NiTObjectArray.h>
#include <EditorAPI/N/NiTransform.h>
#include <EditorAPI/N/NiTSimpleArray.h>
#include <EditorAPI/N/NiTypes.h>

#include <EditorAPI/T/TESBoundAnimObject.h>
#include <EditorAPI/T/TESBoundObject.h>
#include <EditorAPI/T/TESChildCell.h>
#include <EditorAPI/T/TESDataHandler.h>
#include <EditorAPI/T/TESDialogSpell.h>
#include <EditorAPI/T/TESFile.h>
#include <EditorAPI/T/TESForm.h>
#include <EditorAPI/T/TESFullName.h>
#include <EditorAPI/T/TESIcon.h>
#include <EditorAPI/T/TESLandTexture.h>
#include <EditorAPI/T/TESModel.h>
#include <EditorAPI/T/TESModelTextureSwap.h>
#include <EditorAPI/T/TESObject.h>
#include <EditorAPI/T/TESObjectCELL.h>
#include <EditorAPI/T/TESObjectLAND.h>
#include <EditorAPI/T/TESObjectLIGH.h>
#include <EditorAPI/T/TESObjectREFR.h>
#include <EditorAPI/T/TESTexture.h>
#include <EditorAPI/T/TESTopic.h>
#include <EditorAPI/T/TESTopicInfo.h>
#include <EditorAPI/T/TESValueForm.h>
#include <EditorAPI/T/TESWater.h>
#include <EditorAPI/T/TESWaterForm.h>
#include <EditorAPI/T/TESWeightForm.h>

#include <EditorAPI/IDs.h>